### ISSUE TITLE
not building any more

### ISSUE THREAD

**Issue by comtihon** [choptastic/qdate#17]
`git clone https://github.com/choptastic/qdate.git`
`cd qdate/`
`make`

    ===> Verifying dependencies...
    ===> Fetching erlang_localtime ({git,                                                                                                
                                        "git://github.com/choptastic/erlang_localtime.git",                                          
                                        {branch,master}})                                                                            
    ===> Fetching erlware_commons ({git,                                                                                                 
                                       "git://github.com/erlware/erlware_commons.git",                                               
                                       {branch,master}})                                                                             
    ===> Package not buildable with rebar3: cf-0.2.1
`cf` is a dep of `erlware_commons`.  
`./rebar3 update`

    ===> Updating package index...
    ===> Only existing version of ezmq is 0.2.0 which does not match constraint ~> 0.3.1. Using anyway, but it is not guarenteed to work.
Update not helps :(
Although dep `erlware_commons` builds:
`cd _build/default/lib/erlware_commons/`
`./rebar3 compile`

    ===> Verifying dependencies...
    ===> Fetching cf ({pkg,<<"cf">>,<<"0.2.1">>})
    ===> Version cached at /home/tihon/.cache/rebar3/hex/default/packages/cf-0.2.1.tar is up to date, reusing it
    ===> Compiling cf
    ===> Compiling erlware_commons

**Comment by choptastic** [comment]
Thanks, looks like erlware_commons master branch is broken as a dependency.

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by comtihon** [comment]
@choptastic erlware_commons is building independently, but not building as a part of qdata.

**Comment by comtihon** [comment]
I switch build system to `erlang.mk` in my branch for both `erlware_commons` and `qdate`, it worked for me.
I can made PR, if you want.

**Comment by choptastic** [comment]
I'm glad you were able to get it working for you.  I'm going to stick with rebar (and migrate to rebar3 eventually).

I've got an update here that seems to fix the building problem: https://github.com/choptastic/qdate

I'd love to know if this is sufficient for your needs.

**Comment by comtihon** [comment]
Thanks, it works! Could you please tag it?

**Comment by choptastic** [comment]
Tagged: https://github.com/choptastic/qdate/releases/tag/0.4.2

It's very likely this will be updated to 0.4.3, which binds erlang_localtime back to the original repo - I'm just waiting for a bugfix to be merged (https://github.com/dmitryme/erlang_localtime/pull/24)
