### ISSUE TITLE
Stop custom parser log messages

### ISSUE THREAD

**Issue by jhw** [choptastic/qdate#20]
I've defined a custom date parser which works fine but generates a very large number of console log messages of the form

Trying Parser: iso8601

Is there any way to turn this logging off ?

Thx!

**Comment by choptastic** [comment]
Yup, you'll just want to upgrade to a more recent version. This was fixed
in this commit:

https://github.com/choptastic/qdate/commit/c3b490ec526de8d29cf004d9ef246ec3d63a38bc

Have a good one!

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
