### ISSUE TITLE
UTC unixtime error

### ISSUE THREAD

**Issue by tjheeta** [choptastic/qdate#22]
I was using this library to convert a time to unixtime. 

qdate:set_timezone("UTC")
qdate:to_unixtime("2018-3-25T2:32:00")

now returns an error instead of 1521945120 . 

I believe this is caused by a change in erlang_localtime after bd0083ffe6107537a555133c9b94656ca5c854f3 . 

iex(1)> :qdate.set_timezone("UTC")
:ok
iex(2)> :qdate.to_unixtime("2018-3-25T2:32:00")
** (FunctionClauseError) no function clause matching in :calendar.datetime_to_gregorian_seconds/1
    (stdlib) calendar.erl:137: :calendar.datetime_to_gregorian_seconds(:time_not_exists)
             src/qdate.erl:322: :qdate.to_unixtime/2

**Comment by choptastic** [comment]
Fixed in https://github.com/choptastic/erlang_localtime/commit/c0c4e3e386562c86796ae2af30dd7b38d16b6422 and added a test in https://github.com/choptastic/qdate/commit/6036208bb5794608c8654ae72da893b0913ef93c which verifies that it's working. Thanks for the heads up.

**Comment by tjheeta** [comment]
Thanks for the quick fix.
