### ISSUE TITLE
beginning_minute seems wrong.

### ISSUE THREAD

**Issue by silviucpp** [choptastic/qdate#23]
beginning_minute(Date) ->
    {{Y,M,D},{H,M,_}} = to_date(Date),
    {{Y,M,D},{H,M,0}}.

Based on the code first line will match only in case Minute is equal with Month. Otherwise will fail...

M is used for both

Silviu

**Comment by choptastic** [comment]
Thanks! You're right! I'll fix this shortly.

-Jesse

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by choptastic** [comment]
Fixed with https://github.com/choptastic/qdate/commit/4d42f5eddf7f33d915946d3dca718845c2285c57

Thanks again for pointing it out. I need to add some tests for these new functions.
