### ISSUE TITLE
OTP-19 support

### ISSUE THREAD

**Issue by gbour** [choptastic/qdate#24]
Hi

qdate fail to compile with OTP-19 because of unsupported spec format in erlware-commons 0.15.0.
This as been fixed in release 0.20.0, so qdate rebar.config should be updated to use this version

**Comment by choptastic** [comment]
Thanks for the heads up.  I haven't had a chance to play with Erlang 19 yet, so didn't realize.

I'll probably need to use the rebar.config.script option to support rebar2-based projects (because 0.15.0 of Erlware commons was the last version I can get to compile with rebar2).

**Comment by gbour** [comment]
that's true. erlware-commons > 0.15.0 depends on cf which depends on termcap hex package (not supported by rebar v2).

A quickfix for OTP-19 compilation issue is to add erlware-commons 0.21.0 dependency to my top-project rebar.config. This overrides qdate erlware-commons version.

**Comment by elpaisa** [comment]
Any updates on this issue?

**Comment by choptastic** [comment]
Yes, Erlware, merged in https://github.com/erlware/erlware_commons/pull/107 which fixes this.  I was waiting for them to tag a new release.

In the meantime, you should be able to specify cf 0.2.2 directly in your app's rebar.config to get around it until erlware tags a new release.

For rebar2:

`{cf, ".*", {git, "https://github.com/project-fifo/cf", {tag, "0.2.2"}}}`

For rebar3:

`{cf, "0.2.2"}`

Let me know if this helps!

**Comment by gbour** [comment]
:+1:

**Comment by choptastic** [comment]
While waiting for the EC team to tag a new release, for now I have a temporary fix in place with this commit: https://github.com/choptastic/qdate/commit/fc247e296b0aeb201e55e27ae809689ea094a2cb
