### ISSUE TITLE
Dep conflict with amqp-client / rabbitmq-common

### ISSUE THREAD

**Issue by jhw** [choptastic/qdate#27]
Hi,

This isn't really your problem but just FYI I have a long standing project which has been happily using qdate and amqp_client, suddenly giving me the following

 ==> Errors generating release 
           Duplicated modules: 
    ec_semver_parser specified in erlware_commons and rabbit_common
    ec_semver specified in erlware_commons and rabbit_common

Looks like sometime around 12th Oct 2016 rabbitmq-common introduced some changes including a naming conflict with erlware_commons, as used by qdate.  I have posted an issue asking them maybe to change things

https://github.com/rabbitmq/rabbitmq-common/issues/139

But am just letting you know in case you want to change anything.

I guess I should really be notifying all projects using erlware_commons! But qdate seems like an obvious place to start given it's widely used (by me at least)

Best wishes -

**Comment by choptastic** [comment]
Thank you posting this. Hopefully rabbit changes the prefix of their modules and that solves it.  There's not really anything I can do otherwise.

**Comment by choptastic** [comment]
BTW, I'll keep this open until it's resolved on rabbit's side.
