### ISSUE TITLE
Compilation fails due to deprecated erlware commons

### ISSUE THREAD

**Issue by Spoowy** [choptastic/qdate#40]
The compilation fails on erl 20+ due to some depreciations in erlware_commons which I fixed in my fork: https://github.com/Spoowy/erlware_commons

Cheers,
Erwin

**Comment by Spoowy** [comment]
@choptastic I haven't looked into the code in depth but can you give me a feel of how strongly dependent qdate is from those libraries, erlware_commons and cf?

Maybe it would make sense to get rid of these and make it a stand-alone...

**Comment by choptastic** [comment]
Hi @Spoowy, sorry for the delayed response.  I started writing the results yesterday and got sidetracked.  I take it your compilations issues were resolved based on the responses from fred in https://github.com/erlware/erlware_commons/pull/143

To answer your question of dependencies, qdate is tightly reliant on erlware_commons (qdate's parsing iand formatting engine s based on ec_date, which itself is a fork of dh_date).

**Comment by Spoowy** [comment]
Thanks for the fast reply, I'll fork this and see what I can do with the dependencies as I cannot get the ec to compile (ec_file has an issue with mad but compiles well with rebar3, but ec_date does well and fixing mad is too much yak shaving at the moment).

Cheers
